---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- name: Assert usage debian
  assert:
    that: ansible_os_family == "Debian"
    msg: "This module only works with apt"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    vmagent_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- name: Install a list of packages
  apt:
    update_cache: yes
    pkg:
    - nfdump-sflow
    - nfdump

- name: create data directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop: "{{ flows_dir }}"
