---
- include: install.yml
  become: true
  tags:
    - flow_install

- include: configure.yml
  become: true
  tags:
    - flow_configure

- name: ensure nfdump service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: nfdump
    state: started
    enabled: true
  tags:
    - flow_run`

- name: ensure sfdump service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: sfdump
    state: started
    enabled: true
  tags:
    - flow_run`
