---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-ubuntu-16-04
    image: ubuntu:16.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
